# Generated by Django 2.0 on 2018-02-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_meds_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.TextField(verbose_name='Med name')),
                ('med_comment', models.TextField(verbose_name='Comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='med_left',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='med_names',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='med_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='meds_taken',
        ),
        migrations.AddField(
            model_name='patient',
            name='med',
            field=models.TextField(default=None, verbose_name='Medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
    ]
