# Generated by Django 2.0 on 2018-02-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20180224_1602'),
        ('patients', '0004_survey'),
    ]

    operations = [
    ]
