# Generated by Django 2.0 on 2018-02-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient_list',
        ),
    ]
